### ISSUE TITLE
Query returns with fatal error

### ISSUE THREAD

**Issue by ivomans** [stefanak-michal/thingsdb-php#4]
**Describe the bug**
In a script I try to synchronize data from PHP/Mysql into Thingsdb. It runs smooth for many orderlines, but sometimes there is a strange fatal error. Hope you can clearify what is going wrong or for future usage improve the error message.

The error message:
```
PHP Warning:  unpack(): Type v: not enough input values, need 2 values but only 0 were provided in /var/www/html/vendor/stefa
nak-michal/thingsdb-php/src/ThingsDB.php on line 333
PHP Warning:  Trying to access array offset on false in /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php on
 line 333
PHP Warning:  unpack(): Type c: not enough input values, need 1 values but only 0 were provided in /var/www/html/vendor/stefa
nak-michal/thingsdb-php/src/ThingsDB.php on line 334
PHP Warning:  Trying to access array offset on false in /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php on
 line 334
PHP Fatal error:  Uncaught ThingsDB\error\ConnectException: Received package type mismatch: 0 != 18 in /var/www/html/vendor/s
tefanak-michal/thingsdb-php/src/ThingsDB.php:338
Stack trace:
#0 /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php(267): ThingsDB\ThingsDB->read()
#1 /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php(112): ThingsDB\ThingsDB->send()
#2 /var/www/html/class/thingsdb.php(20): ThingsDB\ThingsDB->query()
#3 /var/www/html/cron/thingsdb.php(35): myThingsDB->query()
#4 /var/www/html/cron/thingsdb.php(15): syncOrders()
#5 {main}
  thrown in /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php on line 338
```

**To Reproduce**
Calling `$mydb->query("@:dbname", "wse(); set_order('".str_replace("'", "’", json_encode($ord))."')");`
Where set_order is a procedure defined in Thingsdb, $ord contains an array with fieldnames+values from a Mysql record with normal ASCII characters.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - PHP 8.3.6
 - ThingsDB Version 1.5.0-alpha15
 - thingsdb-php Library Version v1.0.0

**Comment by stefanak-michal** [comment]
Hi. Thanks for reporting this issue. I will try to find some time this next week to look into it. 

Can you please tell me more about $ord array? What is the data type and max length of mysql columns? So i will use appropriate random data. Maybe you can give some example of this data?

Also how many records are you processing? And by your guess at what amount this issue happens?

Does your thingsdb set_order procedure returns anything?

**Comment by ivomans** [comment]
Hi, thanks for taking time to help me.

For now the cronjob will run a maximum of 100 queries at each job.
A sample data that causes the error:
`
set_order('{"LiproNr":"C161091","OrderVolgnr":"161091","OrderSoort":"K","Typering":"-","WerkStraat":"","WerkPostcode":"","WerkPlaats":"","WerkLand":"NL","Aantal":"1","Eenheid":"-","Omschrijving":"Verkenning simpelste besturing goederenlift","deurtype":"","AfleverLocatie":"","Afleveradres":null,"AfleverPostcode":"","Afleverplaats":"","ObjectRef":"","Object":"","Klant":null,"Plaats":null,"KlantRef":"~","NamensRef":"~","Inkoopnummer":null,"Ordernr":null,"ProjNetwNr":null,"ProjNetwNr2":null,"WBSOnr":"","Artikel":"","Hoofdorder":"","HoofdorderFase":"1","OrderType":"A","HuidigeLeverdatum":"2018-12-31","PlanbordFixed":"N","PlanbordGroep":"2","PlanbordGelijktijdig":"1","PlanbordKleur":"#cccccc","StartMontage":"0000-00-00","Keuringsdatum":null,"AanmaakDD":"2016-06-16","GereedDD":"0000-00-00","GereedDDT":null,"ProjLeiderRef":"1","ChefMontRef":"1","Projectleider":null,"Monteur":null,"Bouwbedrijf":null,"Uitvoerder":null,"OrdTelNr":"","OrdTelNr2":"","OrdGsmNr":"","OrdTelNrStrip":"","OrdTelNr2Strip":"","OrdGsmNrStrip":"","OrdEmail":"","Hoofdartikelgroep":null,"GBrek":"5000","InternVerantw":"IM","OpdrachtBevestVerst":"","MeetTekOntv":"NVT","GemetenDD":"NVT","MaterialenBesteld":"NVT","IngegevenDD":"","ProductieDD":"","OppervlakDD":"NVT","TransportDD":"NVT","MontageDD":"","GereedInkoopDD":"","LevFormRetr":"NVT","OfferteDD":null,"OfferteContactDD":"","MondelingOpdrDD":null,"SchriftelijkOpdrDD":"","IncassoMachtigingDD":"","IncassoStatus":"0","NacalcDD":"","ObfVerstuurdDD":"NVT","ObfRetourDD":"NVT","OplevOndAannDD":"NVT","GewOpdrAanvrDD":"NVT","GewOpdrOntvDD":"NVT","DoorlooptijdMeet":"2","DoorlooptijdTek":"2","Doorlooptijd2":"2","DoorlooptijdProd":"2","Doorlooptijd4":"0","Doorlooptijd5":"0","DoorlooptijdMont":"0","CalcUren":"0.00","MeetUren":"0.00","TekenUren":"0.00","Voorcalc03":"0.00","ProdUren":"0.00","Voorcalc05":"0.00","Voorcalc06":"0.00","MontUren":"0.00","Calc_km":"0.00","Calc_ink":"0.00","Calc_art":"0.00","Calc_deelorder":"0.00","InkMarge":"15","Plaatwerk":"0.00","GrijpAantek":"","Foutief":"-","FactArtikelen":"-","FactuurDatum":null,"RefOrdernr":"","FactStatus":"-","FactType":"N","Stand":"?","FinStand":"Check","Opmerking":"","LaatsteWijz":null,"VrijgaveFacturatie":null,"PrijsOfferte":null,"PrijsOpdracht":null,"PrijsTeFactureren":null,"FactuurBedrag":null,"FactuurNummer":null,"VolgendeFactuur":null,"FactuurPeriodiek":"-","Aantekening":"","InterneLocatie":"","ProdInstr":"","TransportInstr":"","MontInstr":"","DeelleveringDD":"0000-00-00","Nacalc":"0.00","OrderWaarde":"0.00","OrderAfgesloten":"0000-00-00","VertrouwCorresp":"N","Onderhoudscontract":"-","OnderhoudFreq":"0","Leveringskosten":"A","Reiskosten":"-","RayonRoute":"-1","ReiskostenAmt":"0.00","ReiskostenQty":"1","WerkbonNr":"0","KlantKorting":"0","Thing":"0","Created":"2016-06-16 11:56:52","Modified":"2023-01-04 07:58:12"}')
`

The set_order function should return the thing-ID, which will be stored in the Mysql record for future synchronisation:

```
{
  orderRec = json_load(json);
  t = int(orderRec.Thing);
  if (order_show(orderRec)) {
      if (t > 0) {
          rec = thing(t);
      } else {
          rec = new('PlanOrder');
          rec.orderNr = orderRec.LiproNr;
          .addPlanOrder(rec);
          t = rec.id();
      };
  } else {
      if (t > 0) {
          .orders.remove(|x| x.id() == t);
          t = 0;
      };
  };
  if (t > 0) {
      rec.Omschr = orderRec.Omschrijving;
      rec.KlantRef = orderRec.KlantRef;
      rec.WerkPlaats = orderRec.WerkPlaats;
  };
  return t;
}

```

**Comment by stefanak-michal** [comment]
So far i'm unable to reproduce your error. But I've noticed you use older version of ThingsDB. Versions 1.6.2 and 1.6.3 contained some fixes related to json processing. Can you try to update to latest version of ThingsDB?

Btw when you call procedure it is prefered way to call `run` instead of `query`. In your case it would be something like this
```php
$mydb->run("@:dbname", "set_order", [json_encode($ord)]);
```

**Comment by stefanak-michal** [comment]
I will share my thoughts. 

If I'm in your position I would try to run procedure `set_order` through ThingsDB GUI, if you are not familiar you can get it here https://github.com/thingsdb/ThingsGUI/releases ..to see if the problem is in ThingsDB or php driver.

Next if problem is related to php, I would try to print out received header. Somewhere here before this throw https://github.com/stefanak-michal/thingsdb-php/blob/408b739e7721f00099f5b5bdfabd2c77800da474/src/ThingsDB.php#L338 Because the error message you posted is showing type check error 0 !=18. That means `check` value is correct, 18 is data. But why `type` is 0, I don't know.

Afterwards I would try to ignore this mismatch and if data length > 0 I will try to consume data. I would propably just comment out that throw, because few lines later is data read.

**Comment by joente** [comment]
@stefanak-michal , In the code I see that multiple calls to `read()` can be done (the `listening()` function too is calling `read()`). 

What happens if one call to `read()` is capturing a part of a package, and another call is capturing another part before the next call to `stream_get_contents` is done (so before `read()` is finished)? On the socket, packages are not mixed, but they might be send in chunks. Could this be the problem? If that case one call to `read()` would not "start" at the beginning of a package but enter in the middle.

**Comment by ivomans** [comment]
Running the call in ThingsGUI is no problem.
Header when error occurs is only a single emoticon: ☺

Btw: using run procedure instead of query is complicated, since run procedure does not simply return the return value.

**Comment by stefanak-michal** [comment]
> @stefanak-michal , In the code I see that multiple calls to `read()` can be done (the `listening()` function too is calling `read()`).
> 
> What happens if one call to `read()` is capturing a part of a package, and another call is capturing another part before the next call to `stream_get_contents` is done (so before `read()` is finished)? On the socket, packages are not mixed, but they might be send in chunks. Could this be the problem? If that case one call to `read()` would not "start" at the beginning of a package but enter in the middle.

While you listen you can't send another query/run. When you listen you just wait. PHP is not event-driven and naturally it doesn't have parallel/async/etc.

**Comment by stefanak-michal** [comment]
> Running the call in ThingsGUI is no problem. Header when error occurs is only a single emoticon: ☺


header is in binary, so it's good practice to show it as hex. You can use something like this:

```php
// $str contains received binary data
$str = implode(unpack('H*', $str));
echo '<pre>';
foreach (str_split($str, 8) as $chunk) {
    echo implode(' ', str_split($chunk, 2));
    echo '    ';
}
echo '</pre>' . PHP_EOL;
```

> Btw: using run procedure instead of query is complicated, since run procedure does not simply return the return value.

I'm not sure if I follow. Method `run` does return what procedure returns. What do you mean exactly?

**Comment by ivomans** [comment]
With following modification:
```
$h = implode(unpack('H*', $header));
$hdr = '';
foreach (str_split($h, 8) as $chunk) {
   $hdr .= '/'.implode(' ', str_split($chunk, 2));
}
```

Result when error occurs: `hdr=/01 00 00 00/e0 00 12 ed`

**Comment by ivomans** [comment]
Please ignore my remark regarding run procedure: my mistake. Run procedure is working just as well, but ending up with exactly same error in hdr.

**Comment by stefanak-michal** [comment]
So I think I found the problem. https://github.com/stefanak-michal/thingsdb-php/compare/master...4-unpack-error

@ivomans Can you try this change/branch, if it helps?

**Comment by ivomans** [comment]
Yes, you solved it ! 
Running without any problem now.

**Comment by stefanak-michal** [comment]
I'm sorry, my mistake. Somehow i forget that. Thanks for reporting and helping with diagnosis. 

New release is out.

**Comment by ivomans** [comment]
Thanks for solving the problem this quick.
