### ISSUE TITLE
Fatal error on authentication error

### ISSUE THREAD

**Issue by ivomans** [stefanak-michal/thingsdb-php#6]
When the auth() function is called with invalid credentials this causes now a PHP Fatal error.
I would expect the function to return a boolean value False.

```
PHP Fatal error:
Uncaught ThingsDB\\error\\PackageException: invalid username or password in /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php:353
Stack trace:
#0 /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php(267): ThingsDB\\ThingsDB->read()
#1 /var/www/html/vendor/stefanak-michal/thingsdb-php/src/ThingsDB.php(82): ThingsDB\\ThingsDB->send()
#2 /var/www/html/class/thingsdb.php(9): ThingsDB\\ThingsDB->auth()
...
```

**Config:**
 - Docker -> Ubuntu 24.04
 - PHP Version 8.3.6
 - ThingsDB Version 1.6.5
 - thingsdb-php Library Version 1.0.1

**Comment by stefanak-michal** [comment]
Response from ThingsDB returns type. In case of error library throws error. https://docs.thingsdb.io/v1/connect/socket/#response-type

So the behaviour is as should. Even if you execute query and it ends with error it will throw exception.
